"""initial schema

Revision ID: 483b2c765511
Revises: 
Create Date: 2026-07-05 00:03:53.610948

"""
from alembic import op
import sqlalchemy as sa


revision = '483b2c765511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('normalised_address', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'normalised_address', name='uq_geocode_cache_key')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'endpoint', 'key', name='uq_idempotency_key')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_org_status', 'jobs', ['organisation_id', 'status'], unique=False)
    op.create_table('matrix_cache',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('origin_key', sa.String(length=48), nullable=False),
    sa.Column('destination_key', sa.String(length=48), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'origin_key', 'destination_key', name='uq_matrix_cache_key')
    )
    op.create_table('organisations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('operating_rules', sa.JSON(), nullable=False),
    sa.Column('webhook_secret', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('driver_id', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('decision_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=True),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('decision_type', sa.String(length=48), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('rules_applied', sa.JSON(), nullable=False),
    sa.Column('decision_result', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audits_plan', 'decision_audits', ['plan_id'], unique=False)
    op.create_table('dispatch_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('planning_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(length=32), nullable=True),
    sa.Column('previous_plan_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_org_status', 'dispatch_plans', ['organisation_id', 'status'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('shift_start', sa.DateTime(), nullable=False),
    sa.Column('shift_end', sa.DateTime(), nullable=False),
    sa.Column('assigned_vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('safety_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drivers_org_status', 'drivers', ['organisation_id', 'status'], unique=False)
    op.create_table('operational_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('driver_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'dedupe_key', name='uq_event_dedupe')
    )
    op.create_index('ix_events_org_type', 'operational_events', ['organisation_id', 'event_type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('raw_address', sa.Text(), nullable=False),
    sa.Column('normalised_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocoding_confidence', sa.Float(), nullable=True),
    sa.Column('geocoding_provider', sa.String(length=64), nullable=True),
    sa.Column('package_weight', sa.Float(), nullable=False),
    sa.Column('package_volume', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('delivery_window_start', sa.DateTime(), nullable=False),
    sa.Column('delivery_window_end', sa.DateTime(), nullable=False),
    sa.Column('service_time_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'external_order_id', name='uq_order_external_id')
    )
    op.create_index('ix_orders_org_status', 'orders', ['organisation_id', 'status'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('registration_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('maximum_weight', sa.Float(), nullable=False),
    sa.Column('maximum_volume', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'registration_number', name='uq_vehicle_registration')
    )
    op.create_table('address_reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('normalised_address', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('driver_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_location', sa.JSON(), nullable=False),
    sa.Column('end_location', sa.JSON(), nullable=False),
    sa.Column('estimated_distance', sa.Float(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=False),
    sa.Column('capacity_usage', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['dispatch_plans.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routes_plan', 'routes', ['plan_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=False),
    sa.Column('estimated_departure', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_number', name='uq_stop_sequence')
    )
    op.create_index('ix_stops_order', 'route_stops', ['order_id'], unique=False)
    op.create_index('ix_stops_route', 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stops_route', table_name='route_stops')
    op.drop_index('ix_stops_order', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('ix_routes_plan', table_name='routes')
    op.drop_table('routes')
    op.drop_table('address_reviews')
    op.drop_table('vehicles')
    op.drop_index('ix_orders_org_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_events_org_type', table_name='operational_events')
    op.drop_table('operational_events')
    op.drop_index('ix_drivers_org_status', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_plans_org_status', table_name='dispatch_plans')
    op.drop_table('dispatch_plans')
    op.drop_index('ix_audits_plan', table_name='decision_audits')
    op.drop_table('decision_audits')
    op.drop_table('api_keys')
    op.drop_table('organisations')
    op.drop_table('matrix_cache')
    op.drop_index('ix_jobs_org_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('idempotency_keys')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
